[profile.default]
  evm_version = "paris"
  optimizer = true
  optimizer_runs = 10_000_000
  remappings = [
    "lib/wormhole/ethereum:@openzeppelin/contracts=lib/openzeppelin-contracts-4/contracts",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts",
    "wormhole/=lib/wormhole/ethereum/contracts",
    "wormhole-sdk/=lib/wormhole-solidity-sdk/src",
    "src/=src/",
    "test/=test/",
    "script/=script/",
  ]
  solc_version = "0.8.23"
  verbosity = 3

[profile.ir]
  via_ir = true

[profile.ci]
  fuzz = { runs = 5000 }
  invariant = { runs = 1000 }

[profile.lite]
  fuzz = { runs = 50 }
  invariant = { runs = 10 }
  # Speed up compilation and tests during development.
  optimizer = false

[fmt]
  bracket_spacing = false
  int_types = "long"
  line_length = 120
  multiline_func_header = "attributes_first"
  number_underscore = "thousands"
  quote_style = "double"
  single_line_statement_blocks = "single"
  tab_width = 2
  wrap_comments = true

[rpc_endpoints]
  holesky = "${HOLESKY_RPC_URL}"
  mainnet = "${ETHEREUM_RPC_URL}"
  optimism_sepolia = "${OPTIMISM_SEPOLIA_RPC_URL}"
  sepolia = "${SEPOLIA_RPC_URL}"
  holesky = "${HOLESKY_RPC_URL}"

[etherscan]
 sepolia = { key = "${ETHERSCAN_API_KEY}" }
 holesky = { key = "${ETHERSCAN_API_KEY}" }
