anchor_version = "0.30.1"

[features]
seeds = true

[workspace]
members = ["programs/staking"]

[programs.localnet]
staking = "5Vry3MrbhPCBWuviXVgcLQzhQ1mRsVfmQyNFuDgcPUAQ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "./app/keypairs/localnet_authority.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/staking.ts"

[validator]
ledger_dir = "./.anchor/test-ledger"

[path]
idl_path = "./target/idl/staking.json"
binary_path = "./target/deploy/staking.so"

