anchor_version = "0.28.0"

[features]
seeds = true

[workspace]
members = ["programs/staking"]

[programs.localnet]
staking = "pytS9TjG1qyAZypk7n8rw8gfW9sUaqqYyMhJQ4E7JCQ"
chat = "gCHAtYKrUUktTVzE4hEnZdLV4LXrdBf6Hh9qMaJALET"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "./app/keypairs/localnet_authority.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/staking.ts"

[validator]
ledger_dir = "./.anchor/test-ledger"

[path]
idl_path = "./target/idl/staking.json"
binary_path = "./target/deploy/staking.so"
chat_path = "./target/deploy/chat.so"
