[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
staking = "9ZEwtMdK5AumsSss8PiEb3VQhR7mTpvrSzdcdM95Uduh"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "Localnet"
wallet = "./app/keypairs/localnet_authority.json"

[workspace]
members = ["programs/staking"]

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
