[package]
name = "external_program"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = { version = "0.30.1", features = ["init-if-needed"] }

[profile.release]
overflow-checks = true

[features]
idl-build = ["anchor-lang/idl-build"]
