name: Solana
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  CARGO_TERM_COLOR: always
defaults:
    run:
        working-directory: solana
jobs:
  tests:
    runs-on: ubuntu-latest
    container: backpackapp/build:v0.30.1

    steps:
      - uses: actions/checkout@v4
      - name: List rustup toolchains
        run: rustup toolchain list
      - name: Set default toolchain
        run: rustup default stable
      - name: List rustup toolchains
        run: rustup toolchain list
      - name: Install dependencies
        run: npm install
      - name: Anchor build
        run: |
          cargo build 
          cargo test 
          npm run build_wasm 
          anchor build
      - name: Anchor tests
        run: anchor test